version: '3.8'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env
    environment:
      PG_URL: ${PG_URL}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:16.2-alpine3.18
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine3.19
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
    name: jetei-postgres
  
